In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd
from datetime import datetime
import turfpy as tp

In [2]:
mongo = MongoClient(port=27017)

In [8]:
!mongoimport --type csv -d travel  -c destination --headerline --drop "destination.csv"

2023-04-20T17:21:30.017-0500	connected to: mongodb://localhost/
2023-04-20T17:21:30.018-0500	dropping: travel.destination
2023-04-20T17:21:30.041-0500	49 document(s) imported successfully. 0 document(s) failed to import.

In [9]:
db = mongo.travel# database
dest= db.destination # collection

In [10]:

print(db.list_collection_names())

['destination']

In [11]:
db = pd.DataFrame(list(dest.find()))

In [12]:
db

,_id,date\tAirline\tflight no\tdest airport\tdestination lat\tdestination long
0,6441baeae9f37be8c66c6cae,2015-02-04\tTransasia\tGE235\tKHN\t28.6\t115.917
1,6441baeae9f37be8c66c6caf,2015-06-30\tSumatra Indonesian Air Force Civil...
2,6441baeae9f37be8c66c6cb0,2015-08-16\tTrigana Air Service\tIL267\tOKL\t-...
3,6441baeae9f37be8c66c6cb1,2015-09-05\tSenegalair\tC271\tSSG\t3.755\t8.709
4,6441baeae9f37be8c66c6cb2,2015-10-31\tMetrojet\t7K9268\tLED\t59.8\t30.265
5,6441baeae9f37be8c66c6cb3,2016-01-08\tWest Air Sweden\tPT294\tTOS\t69.68...
6,6441baeae9f37be8c66c6cb4,2016-02-02\tDaallo Airlines\tD3159\tJIB\t11.54...
7,6441baeae9f37be8c66c6cb5,2016-02-24\tTara Air\tTB193\tJMO\t28.78\t83.723
8,6441baeae9f37be8c66c6cb6,2016-03-09\tTrue Aviation Ltd.\tAN21\tIXZ\t11....
9,6441baeae9f37be8c66c6cb7,2016-03-19\tFlydubai\tFZ981\tROV\t47.258\t39.818
10,6441baeae9f37be8c66c6cb8,2016-04-29\tCHC Helikopter Service\tHKS241\tBG...
11,6441baeae9f37be8c66c6cb9,2016-05-19\tEgyptair\tMS804\tCAI\t30.122\t31.406
12,6441baeae9f37be8c66c6cba,2016-08-05\tEmirates\tEK521\tDXB\t25.255\t55.364
13,6441baeae9f37be8c66c6cbb,2016-08-31\tHageland Aviation\tH63190\tTOG\t59...
14,6441baeae9f37be8c66c6cbc,2016-11-28\tLaMia Bolivia\tLM2933\tMDE\t6.164\...
15,6441baeae9f37be8c66c6cbd,2015-03-24\tGermanwings\t4U9525\tDUS\t51.289\t...
16,6441baeae9f37be8c66c6cbe,2016-12-07\tPakistan International Airlines\tP...
17,6441baeae9f37be8c66c6cbf,2016-12-20\tAerosucre Colombia\t6C157\tBOG\t4....
18,6441baeae9f37be8c66c6cc0,2017-01-16\tTurkish Airlines\tTK6491\tFRU\t43....
19,6441baeae9f37be8c66c6cc1,2017-05-05\tAir Cargo Carriers\t2Q1260\tCRW\t3...
20,6441baeae9f37be8c66c6cc2,2017-05-27\tSummit Air\tSMA409\tLUA\t48.031\t-...
21,6441baeae9f37be8c66c6cc3,2017-12-13\tWest Wind Aviation\tWEW282\tYSK\t5...
22,6441baeae9f37be8c66c6cc4,2017-12-31\tNature Air\t5C9916\tSJO\t9.994\t-8...
23,6441baeae9f37be8c66c6cc5,2018-02-18\tIran Aseman Airlines\tEP3704\tYES\...
24,6441baeae9f37be8c66c6cc6,2018-03-12\tUS-Bangla Airlines\tBS211\tKTM\t27...
25,6441baeae9f37be8c66c6cc7,2018-02-11\tSaratov Airlines\t6W703\tOSW\t51.0...
26,6441baeae9f37be8c66c6cc8,2018-04-17\tSouthwest Airlines\tWN1380\tDAL\t3...
27,6441baeae9f37be8c66c6cc9,2018-05-18\tCubana (leased from Global Air)\tC...
28,6441baeae9f37be8c66c6cca,2018-09-28\tAir Niugini\tPX73\tPOM\t-9.443\t14...
29,6441baeae9f37be8c66c6ccb,2018-10-29\tLion Air\tJT610\tPGK\t-2.163\t106.139
30,6441baeae9f37be8c66c6ccc,2018-11-06\tFly Jamaica Airways\tOJ256\tYYZ\t4...
31,6441baeae9f37be8c66c6ccd,2019-02-23\tAtlas Air serving Amazon\t5Y3591\t...
32,6441baeae9f37be8c66c6cce,2019-03-10\tEthiopian Airlines\tET302\tNBO\t-1...
33,6441baeae9f37be8c66c6ccf,2019-05-05\tAeroflot Russian International Air...
34,6441baeae9f37be8c66c6cd0,2019-10-04\tUkraine Air Alliance\tUKL4050\tIST...
35,6441baeae9f37be8c66c6cd1,2019-12-27\tBek Air\tZ92100\tNQZ\t-45.02\t168.741
36,6441baeae9f37be8c66c6cd2,2020-01-08\tUkraine International Airlines\tPS...
37,6441baeae9f37be8c66c6cd3,2020-02-05\tPegasus Airlines\tPC2193\tSAW\t46....
38,6441baeae9f37be8c66c6cd4,2020-05-22\tPakistan International Airline\tPK...
39,6441baeae9f37be8c66c6cd5,2020-08-07\tAir India Exppress\tIX1344\tCCJ\t1...
40,6441baeae9f37be8c66c6cd6,2021-01-09\tSriwijaya Air\tSJ182\tPNK\t-0.151\...
41,6441baeae9f37be8c66c6cd7,2021-07-06\tKamchatka Air Enterprise\tPTK251\t...
42,6441baeae9f37be8c66c6cd8,2022-11-06\tPrecision Air\tPW494\tBKZ\t-1.33\t...
43,6441baeae9f37be8c66c6cd9,2022-11-18\tLATAM Peru\tLP2213\tJUL\t-15.467\t...
44,6441baeae9f37be8c66c6cda,2022-05-29\tTara Air\tTB197\tJMO\t28.78\t83.723
45,6441baeae9f37be8c66c6cdb,2023-01-15\tYeti Airlines\tYT691\tPKR\t28.2\t8...
46,6441baeae9f37be8c66c6cdc,2021-09-12\tAeroservice/SiLA\tHZ51\tKJA\t56.17...
47,6441baeae9f37be8c66c6cdd,2022-07-16\tMeridian\tMRM3032\tDAC\t23.843\t90...
48,6441baeae9f37be8c66c6cde,2022-03-22\tChina Eastern Airlines\tMU5735\tCA...